apiVersion: apps/v1
kind: Deployment
metadata:
  name: configwebapp
  labels:
    app: configwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configwebapp
  template:
    metadata:
      labels:
        app: configwebapp
    spec:
      containers:
        - name: configwebapp
          image: docker.io/ashafqat/configimage:v1.0
          # image: devadeelregistry.azurecr.io/adshafqatupwork:8        
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          # This section is only required if you are attaching a volume like a config map or secret to your application
          volumeMounts:
          - mountPath: /etc/config
            name: config
            readOnly: true
          ####
      # This section is only required if you are attaching a volume like a config map or a secret to your application
      volumes:
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: configwebappcm
            items:
            - key: "application.properties"
              path: "application.properties"
        ####
